"""init

Revision ID: 2759ec0bf5ea
Revises: 
Create Date: 2020-12-15 17:18:41.171795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2759ec0bf5ea'
down_revision = None
branch_labels = None
depends_on = None


GlobalRoleEnum = sa.Enum('owner', 'employee', name='global_role_enum')
ProjectRoleEnum = sa.Enum('admin', 'manager', name='project_role_enum')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # COMPANY
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),

    sa.PrimaryKeyConstraint('id', name=op.f('pk__company'))
    )

    # PROJECT
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),

    sa.ForeignKeyConstraint(
        ['company_id'],
        ['company.id'],
        name=op.f('fk__project__company_id__company')
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__project'))
    )

    # USER
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('owner', 'employee', name='global_role_enum'), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),

    sa.ForeignKeyConstraint(
        ['company_id'],
        ['company.id'],
        name=op.f('fk__user__company_id__company')
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user'))
    )

    # MEMBERSHIP
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', name='project_role_enum'), nullable=True),

    sa.ForeignKeyConstraint(
        ['project_id'],
        ['project.id'],
        name=op.f('fk__membership__project_id__project')
    ),
    sa.ForeignKeyConstraint(
        ['user_id'],
        ['users.id'],
        name=op.f('fk__membership__user_id__user')
    ),

    sa.PrimaryKeyConstraint('id', name=op.f('pk__membership'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membership')
    op.drop_table('users')
    op.drop_table('project')
    op.drop_table('company')
    GlobalRoleEnum.drop(op.get_bind(), checkfirst=False)
    ProjectRoleEnum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
